[build]
  publish = "public"
  command = "composer install"

[context.production]
  command = "docker build -t my-php-app . && docker run -p 8080:80 my-php-app"

[[plugins]]
  package = "@netlify/plugin-docker"
